#!/usr/bin/expect

# exp_internal 1   ;# diagnostics

set spawn_tagsh "spawn ../bin/tagsh --db -"
set bootstrap ../bootstrap.tagl

set PROMPT "tagd> "
set MAX_ERRORS 3
set ERRORS 0
set NL "\r\n"   ;# WTF
set TIMEOUT 1

set timeout $TIMEOUT
set log_user 1  ;# log output to stdout, 0 disables

proc test_pass {n} {
	puts "\n****** $n passed ******\n"
}

proc test_fail {n} {
	puts "\n^^^^^^ $n failed ^^^^^^\n"
}

# sends a tagls string and expects args
# n = <test_name>, s = <tagl_string>, e = <expect_args>
proc test {n s e} {
	upvar 1 ERRORS errors
	upvar 1 MAX_ERRORS max_errors
	upvar 1 NL nl
	upvar 1 PROMPT prompt

	set match 0

	send "$s$nl"
	expect "$s$nl"	;# eat the echoed statement

	expect {
		-regexp $e  { 
				test_pass $n
				set match 1
			}
	}

	# eats output up to the next prompt
	expect $prompt

	if {$match} { return }

	test_fail $n
	incr errors

	if {$errors >= $max_errors} {
		puts "$errors errors. Exiting..."
		exit $errors
	}
}

# like test, but fails if the expect args are true
# use sparingly because it has to timeout for success
proc test_neg {n s e} {
	upvar 1 ERRORS errors
	upvar 1 MAX_ERRORS max_errors
	upvar 1 NL nl
	upvar 1 PROMPT prompt

	set match 0	

	send "$s$nl"
	expect "$s$nl"	;# eat the echoed statement

	expect {
		-regexp $e  { 
				test_fail $n
				incr errors

				if {$errors >= $max_errors} {
					puts "$errors errors. Exiting..."
					exit $errors
				}

				set match 1	
			}
		default		;# timeout,eof ok
	}

	# eats output up to the next prompt
	expect $prompt

	if {$match} { return }  ;# failed

	test_pass $n
}

eval $spawn_tagsh
expect "use .show to list commands$NL"
expect $PROMPT

# passes when output does not contain TAGL_ERR or "no such file"
test_neg "bootstrap" \
	     ".load $bootstrap" \
	     "(TAGL_ERR)|(no such file)"

test_neg "bootstrap_quiet" \
	     ".load $bootstrap" \
	     "-- TAGD_OK"

test "bootstrap_reload_duplicate" \
	 ".load $bootstrap" \
	 "_error:ts_duplicate"

send "%% _context simple_english$NL"
expect "%% _context simple_english$NL"
expect $PROMPT

test "put_url_dog" \
     ">> https://en.wikipedia.org/wiki/Dog about dog has title = \"Dog - Wikipedia, the free encyclopedia\"" \
	 "TAGD_OK"

test "get_url_dog" \
     "<< https://en.wikipedia.org/wiki/Dog ;" \
	 "https://en.wikipedia.org/wiki/Dog(.*)about dog"

test "put_url_dog2" \
    ">> http://animal.discovery.com/breed-selector/dog-breeds.html about dog" \
	"TAGD_OK"

test "put_url_cat" \
    ">> https://en.wikipedia.org/wiki/Cat about cat" \
	"TAGD_OK"

test "tag_sub_search" \
	 "?? _interrogator _sub animal _has _terms = \"warm blood\";" \
	 "mammal"

test "tag_sub_symbol_search" \
	 "?? _interrogator =: animal -> _terms = \"warm blood\";" \
	 "mammal"

test "search" \
	 "?? \"dog\";" \
	"https://en.wikipedia.org/wiki/Dog, http://animal.discovery.com/breed-selector/dog-breeds.html, dog"

test "query_url_dog" \
     "?? what is_a _url about dog" \
	"https://en.wikipedia.org/wiki/Dog, http://animal.discovery.com/breed-selector/dog-breeds.html"

test "query_url_animal" \
     "?? what is_a _url * animal" \
	"https://en.wikipedia.org/wiki/Dog, http://animal.discovery.com/breed-selector/dog-breeds.html, https://en.wikipedia.org/wiki/Cat"

test "query_url_animal_wikipedia" \
	"?? what is_a _url * animal
	_has _private = wikipedia, _public = org" \
	"https://en.wikipedia.org/wiki/Dog, https://en.wikipedia.org/wiki/Cat"

send ".exit$NL"
expect eof
wait

if {$ERRORS} {
	puts "$ERRORS errors."
} else {
	puts "All tests passed."
} 

exit $ERRORS
